---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
data <-read.csv ("activity/activity.csv")
data$date <- as.Date(data$date)

```

## What is mean total number of steps taken per day?
```{r}
library(dplyr)
steps_taken_per_day <- summarise(group_by(data, date),total_steps=sum(steps,na.rm=TRUE))
hist(steps_taken_per_day$total_steps,main='Total number of steps taken per day',xlab='Steps per day',col='red')
mean(steps_taken_per_day$total_steps,na.rm=TRUE)
median(steps_taken_per_day$total_steps,na.rm=TRUE)
```
## What is the average daily activity pattern?
```{r}
average_steps_per_interval <- summarise(group_by(data,interval),average_per_interval=mean(steps,na.rm=TRUE))
with(average_steps_per_interval,plot(interval,average_per_interval,type = "l",main='Average number of steps taken per interval',xlab='Interval',ylab='Average number of steps',col='blue'))
with(average_steps_per_interval,interval[which.max(average_per_interval)])

```
## Imputing missing values
Strategy: NA values will be replaced by the mean value with the mean for 5-minute interval.
```{r}
sum(is.na(data$steps)|is.na(data$date)|is.na(data$interval))
data_all <- inner_join(data,average_steps_per_interval)
data_filled <- mutate(data_all,steps=ifelse(is.na(steps),average_per_interval,steps))
data_filled <- select(data_filled,-average_per_interval)
data_filled <- summarise(group_by(data_filled, date),total_steps=sum(steps,na.rm=TRUE))
hist(data_filled$total_steps,main='Total number of steps taken per day',xlab='Steps per day',col='green')
mean(data_filled$total_steps,na.rm=TRUE)
median(data_filled$total_steps,na.rm=TRUE)

```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
library(lubridate)
data_weekly<-mutate(data,day=as.factor(ifelse(wday(date) %in% c(1,7),"weekend","weekday")))
data_day_interval<- summarise(group_by(data_weekly,day,interval), average=mean(steps,na.rm=TRUE))
library(lattice)
with (data_day_interval, 
      xyplot(average ~ interval|day, type="l", 
             ylab="Number of steps",xlab='Interval',layout=c(1,2)))

```


